services:
  relay:
    image: example/relay:1.2.3
    deploy:
      restart_policy:
        condition: any
    ports:
      - target: 3478
        published: 3478
        protocol: udp
        mode: host
    labels:
      - "vps.expose.udp=3478"
